#!/bin/bash

# Using set -e, we exit immediately on any failure. This will help to warn us if the backups didn't completed given the last Dead Man's Snitch
#However, no snitches yet configured
#set -e

echo "mkdir `hostname`" | sftp u109852@u109852.your-backup.de
DEST=sftp://u109852@u109852.your-backup.de/`hostname`/
BACKUPLIST="dbbackups backups"


#Cleaning up some older backups

duplicity remove-all-but-n-full 4 --force $DEST
duplicity remove-all-inc-but-n-full 2 --force $DEST


for i in $BACKUPLIST
do
	duplicity full /data/$i $DEST
	duplicity verify --compare-data $DEST /data/$i
done


#The line below should be configured for each server separately
#Ie. this should be a template and filled in accordingly...

#curl -q -s https://nosnch.in/SnitchString > /dev/null

